export const DEFAULT_SECRET_SALT = "STORAGE_SIGNATURE_SALT";
export const DEFAULT_BROADCAST_CHANNEL = "STORAGE_BROADCAST_CHANNEL";
export const DEFAULT_DB_NAME = "STORAGE_DATABASE_NAME";
export const DEFAULT_STORE_NAME = "STORAGE_OBJECT_STORE";
export const DEFAULT_MAX_ITEMS = 1000;
